### ISSUE TITLE
抓取到的資料會重複出現

### ISSUE THREAD

**Issue by a37125460-Yuki** [scsa3/coolpc-parser#1]
不好意思打擾一下
我發現抓取下來的資料會重複出現
網頁中class行的3.5吋 SATA3 傳統碟其實就抓取到所有資料了
3.5吋 SATA3 監控碟行開始又會再重複抓取已抓取過的資料
這樣class分類會錯誤並且資料也有重複

想請問有辦法修復這問題嗎?

**Comment by a37125460-Yuki** [comment]
internal_hdd.py該檔案28行開始改成這樣可以修復問題
但是這寫法有點low

> def get_options(self):
>         options = list()
>         count = 0
>         for group in self.optgroups:
>             count += 1
>             if count > 1:
>                 break
>             for option_tag in group.find_all("option"):
>                 if option_tag.has_attr("disabled"):
>                     continue
>                 subtitle = option_tag.parent.get("label")
>                 a_option = InternalHddOption(self.title, subtitle, option_tag.text)
>                 options.append(a_option)
>         return options

**Comment by scsa3** [comment]
> internal_hdd.py該檔案28行開始改成這樣可以修復問題
> 但是這寫法有點low
> 
> > def get_options(self):
> > options = list()
> > count = 0
> > for group in self.optgroups:
> > count += 1
> > if count > 1:
> > break
> > for option_tag in group.find_all("option"):
> > if option_tag.has_attr("disabled"):
> > continue
> > subtitle = option_tag.parent.get("label")
> > a_option = InternalHddOption(self.title, subtitle, option_tag.text)
> > options.append(a_option)
> > return options

@a37125460-Yuki
剛看了很久發現原來原價屋很多html tag都沒有close，寫了個workaround的方法，再麻煩你檢查一下有沒有用，感謝。
